/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ModuloAdmin;
import controladores.ControladorConfiguracion;
import ds.desktop.notify.DesktopNotify;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fenix
 */
public class Pn_ConfServer extends javax.swing.JPanel {
     ControladorConfiguracion cc = new ControladorConfiguracion();
    

    /**
     * Creates new form NuevoEmpleado1
     */
    public Pn_ConfServer() {
        initComponents();
        initComponents();
        cargarConfiguraciones();
    }

     public void cargarConfiguraciones() {
        this.jt_Servidor.setText(cc.getServer());
        this.jt_Instancia.setText(cc.getInstance());
        this.jt_Puerto.setText(cc.getPort());
        this.jt_BD.setText(cc.getDatabase());
        this.jt_Usuario.setText(cc.getUser());
        this.jt_Password.setText(cc.getPassword());
    }
   public Boolean validarEscritura() {
        Boolean val = true;
        //si el textfield tiene algo diferente a Vacío aparecerá de color negro
       if (!(jt_Servidor.getText().equals("jTextField1")) && !(jt_Servidor.getText().equals(""))) {
           lb_errorServidor.setForeground(new Color(84, 110, 122));
       } else {
           lb_errorServidor.setForeground(Color.RED);
           val = false;
       }
       //si el textfield tiene algo diferente a Vacío aparecerá de color negro
       if (!(jt_Instancia.getText().equals("jTextField1")) && !(jt_Instancia.getText().equals(""))) {
           lb_errorInstancia.setForeground(new Color(84, 110, 122));
       } else {
           lb_errorInstancia.setForeground(Color.RED);
           val = false;
       }
       //si el textfield tiene algo diferente a Vacío aparecerá de color negro
       if (!(jt_Puerto.getText().equals("jTextField1")) && !(jt_Puerto.getText().equals(""))) {
           lb_errorPuerto.setForeground(new Color(84, 110, 122));
       } else {
           lb_errorPuerto.setForeground(Color.RED);
           val = false;
       }
               //si el textfield tiene algo diferente a Vacío aparecerá de color negro
        if (!(jt_BD.getText().equals("jTextField1")) && !(jt_BD.getText().equals(""))) {
            lb_errorBD.setForeground(new Color(84, 110, 122));
        } else {
            lb_errorBD.setForeground(Color.RED);
            val = false;
        }
        //si el textfield tiene algo diferente a Vacío aparecerá de color negro
        if (!(jt_Usuario.getText().equals("jTextField1")) && !(jt_Usuario.getText().equals(""))) {
            lb_errorUsuario.setForeground(new Color(84, 110, 122));
        } else {
            lb_errorUsuario.setForeground(Color.RED);
            val = false;
        }
                //si el textfield tiene algo diferente a Vacío aparecerá de color negro
        if (!(jt_Password.getPassword().equals("jTextField1")) && !(jt_Password.getPassword().equals(""))) {
            lb_errorPassword.setForeground(new Color(84, 110, 122));
        } else {
            lb_errorPassword.setForeground(Color.RED);
            val = false;
        }
        return val;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jt_Servidor = new javax.swing.JTextField();
        jt_Instancia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt_Puerto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt_BD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jt_Usuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_Password = new javax.swing.JPasswordField();
        lb_errorServidor = new javax.swing.JLabel();
        lb_errorInstancia = new javax.swing.JLabel();
        lb_errorPuerto = new javax.swing.JLabel();
        lb_errorBD = new javax.swing.JLabel();
        lb_errorUsuario = new javax.swing.JLabel();
        lb_errorPassword = new javax.swing.JLabel();
        btnAceptar = new principal.MaterialButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(84, 110, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 110, 122));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Configuración de la conexion ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jLabel2)
                    .addContainerGap(357, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1010, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("SERVIDOR :");

        jt_Servidor.setText("jTextField1");

        jt_Instancia.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("INSTANCIA :");

        jt_Puerto.setText("jTextField1");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PUERTO :");

        jt_BD.setText("jTextField1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("BASE DE DATOS :");

        jt_Usuario.setText("jTextField1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("USUARIO :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CONTRASEÑA :");

        jt_Password.setText("jPasswordField1");

        lb_errorServidor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorServidor.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorServidor.setText("*");

        lb_errorInstancia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorInstancia.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorInstancia.setText("*");

        lb_errorPuerto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorPuerto.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorPuerto.setText("*");

        lb_errorBD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorBD.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorBD.setText("*");

        lb_errorUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorUsuario.setText("*");

        lb_errorPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorPassword.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorPassword.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_errorServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_errorInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_errorPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_errorBD, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_errorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_errorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jt_Servidor, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jt_Instancia)
                    .addComponent(jt_Puerto)
                    .addComponent(jt_BD)
                    .addComponent(jt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Usuario))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_errorServidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lb_errorInstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Instancia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lb_errorPuerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lb_errorBD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lb_errorUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lb_errorPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 440));

        btnAceptar.setBackground(new java.awt.Color(24, 157, 63));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 430, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recomendaciones:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
      try {
            if (!validarEscritura() == true) {

                DesktopNotify.showDesktopMessage("Error", "REVISAR CAMPOS OBLIGATORIOS", DesktopNotify.ERROR);

            } else {

                cc.modificarConexion(jt_Servidor.getText(), jt_Instancia.getText(), jt_Puerto.getText(), jt_BD.getText(), "false", jt_Usuario.getText(), jt_Password.getText());
                cargarConfiguraciones();
            }

        } catch (Exception e) {

            DesktopNotify.showDesktopMessage("Error", "Ocurrió un error al intentar modifcar los datos del servidor"
                    + "por favor intente de nuevo o revise su conexión", DesktopNotify.ERROR);

        }
    }//GEN-LAST:event_btnAceptarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jt_BD;
    private javax.swing.JTextField jt_Instancia;
    private javax.swing.JPasswordField jt_Password;
    private javax.swing.JTextField jt_Puerto;
    private javax.swing.JTextField jt_Servidor;
    private javax.swing.JTextField jt_Usuario;
    private javax.swing.JLabel lb_errorBD;
    private javax.swing.JLabel lb_errorInstancia;
    private javax.swing.JLabel lb_errorPassword;
    private javax.swing.JLabel lb_errorPuerto;
    private javax.swing.JLabel lb_errorServidor;
    private javax.swing.JLabel lb_errorUsuario;
    // End of variables declaration//GEN-END:variables
}
