/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ModuloAdmin;

import controladores.ControladorCategorias;
import controladores.ControladorEscritura;
import controladores.ControladorFormularioTab;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultCaret;
import ds.desktop.notify.DesktopNotify;
import ds.desktop.notify.NotifyTheme;
import java.awt.event.ItemEvent;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.border.LineBorder;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import controladores.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.mail.AuthenticationFailedException;
import javax.swing.DefaultComboBoxModel;
import objetos.*;

/*
    NOTA: SE DEBE CONFIGURAR GMAIL PARA PERMITIR EL ACCESO A APLICACIONES MENOS SEGURAS
    PASOS:
   (1)ICONO DE GMAIL
   (2)CLICK EN "MI CUENTA"
   (3)CLICK EN "INICIO DE SESIÓN Y SEGURIDAD"
   (4)ACTIVAR "PERMITIR EL ACCESO DE APLICACIONES MENOS SEGURAS"
 */
public class Pn_MovimientosCaja extends javax.swing.JPanel {
ControladorUsuarios cuser = new ControladorUsuarios();
    private ControladorReservaciones cr = new ControladorReservaciones();
    private ControladorClientes mc = new ControladorClientes();
    ControladorCFDI cf = new ControladorCFDI();
    //controlador necesario para extraer datos de las tablas reservaciones/cobro reservaciones
    ControladorEnvioFacturacion cenf = new ControladorEnvioFacturacion();
    ControladorEmail cemail = new ControladorEmail();
    ControladorCategorias ccat = new ControladorCategorias();
    ControladorEscritura ce = new ControladorEscritura();
    DefaultTableModel NewTable = new DefaultTableModel();
    private ControladorFormularioTab cft = new ControladorFormularioTab();
    private String correoRemitente, passwordRemitente, correoReceptor, asunto, mensaje;

    //necesario para dar formato al jdateChooser
    private DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    private boolean flag = false;
 //necesario para obtener el numero de fila de la jtable
    private int seleccion;
    /**
     * Creates new form Pn_NuevaCategoria
     */
    public Pn_MovimientosCaja() {
        initComponents();
        RowHeaderApariencia();
        RowApariencia();
        cTabla();
        cargarUsuarios();
        tamañoTabla();

    }
  private void cargarUsuarios() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Usuario");
        for (ObjetoUsuario campos : cuser.selectUsuario()) {
            cb.addElement(campos.getUsername());
        }
        cb_usuario.setModel(cb);

    }
    private void tamañoTabla() {
        TableColumnModel columnModel = jt_Cajas.getColumnModel();

    }

    private void cTabla() {
     
    }

    private void RowApariencia() {

        jt_Cajas.setFocusable(false);
        //espacio entre comulnas
        jt_Cajas.setIntercellSpacing(new Dimension(0, 1));
        //altura de columnas 
        jt_Cajas.setRowHeight(25);
        //margen entre filas
        jt_Cajas.setRowMargin(0);
        //sin lineas verticles
        jt_Cajas.setShowVerticalLines(false);
        jt_Cajas.setSelectionBackground(new Color(97, 212, 195));

    }

    private void RowHeaderApariencia() {
        jt_Cajas.getTableHeader().setFont(new Font("Century Gothic", Font.BOLD, 14));
        jt_Cajas.getTableHeader().setOpaque(false);
        jt_Cajas.getTableHeader().setBackground(Color.BLACK);
        jt_Cajas.getTableHeader().setForeground(new Color(255, 255, 255));

    }


/*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Cajas = new javax.swing.JTable();
        btn_AperturaCaja = new principal.MaterialButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lb_RazonSocial = new javax.swing.JLabel();
        lb_errorEmail = new javax.swing.JLabel();
        lb_errorTelefono = new javax.swing.JLabel();
        lb_errorAsunto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cb_usuario = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(84, 110, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jt_Cajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Cajas.getTableHeader().setResizingAllowed(false);
        jt_Cajas.getTableHeader().setReorderingAllowed(false);
        jt_Cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_CajasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jt_CajasMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Cajas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1000, 320));

        btn_AperturaCaja.setBackground(new java.awt.Color(40, 180, 99));
        btn_AperturaCaja.setForeground(new java.awt.Color(255, 255, 255));
        btn_AperturaCaja.setText("Aperturar  Caja");
        btn_AperturaCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_AperturaCaja.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_AperturaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AperturaCajaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_AperturaCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 250, 40));

        jPanel2.setBackground(new java.awt.Color(84, 110, 122));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modulo de Apertura y Cierre de Cajas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Formulario de Apertura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(170, 136, 119));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Usuario ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 89, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(170, 136, 119));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Monto Inicial");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 89, -1));

        jSeparator4.setBackground(new java.awt.Color(236, 239, 241));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 10));

        lb_RazonSocial.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lb_RazonSocial.setForeground(new java.awt.Color(153, 153, 153));
        lb_RazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_RazonSocial.setText("Razón Social");
        jPanel3.add(lb_RazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, -1));

        lb_errorEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorEmail.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorEmail.setText("*");
        jPanel3.add(lb_errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 10, -1));

        lb_errorTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorTelefono.setText("*");
        jPanel3.add(lb_errorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 10, -1));

        lb_errorAsunto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorAsunto.setForeground(new java.awt.Color(255, 255, 255));
        lb_errorAsunto.setText("*");
        jPanel3.add(lb_errorAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 10, -1));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Ingresar Monto Inicial");
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 210, -1));

        cb_usuario.setBackground(new java.awt.Color(84, 110, 122));
        cb_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar usuario" }));
        cb_usuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuarioItemStateChanged(evt);
            }
        });
        cb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuarioActionPerformed(evt);
            }
        });
        jPanel3.add(cb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 370, 110));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTA DE CAJAS ABIERTAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(592, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1000, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AperturaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AperturaCajaActionPerformed
        try {
            if (btn_AperturaCaja.getText().equals("Aperturar Caja")){
                
            }else if (btn_AperturaCaja.getText().equals("Cerrar Caja")){
                
            }
        } catch (Exception e) {
        }
      
    }//GEN-LAST:event_btn_AperturaCajaActionPerformed

    private void jt_CajasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_CajasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CajasMouseEntered

    private void jt_CajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_CajasMouseClicked
  seleccion = jt_Cajas.rowAtPoint(evt.getPoint());      
 String estado;
 
      
        estado = String.valueOf(jt_Cajas.getValueAt(seleccion, 6));
        if (estado.equals("abierto")) {
            btn_AperturaCaja.setText("Cerrar Caja");
            btn_AperturaCaja.setBackground(new Color(255, 153, 0));
            btn_AperturaCaja.setEnabled(true);
            
            //mamdar a traer en una consulta la suma de todos los gatos generados por ese usuarioS
            
        }else {
            btn_AperturaCaja.setText("Aperturar Caja");
            btn_AperturaCaja.setBackground(new Color(40,180,99));
            btn_AperturaCaja.setEnabled(false);
        }

        

        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CajasMouseClicked

    private void cb_usuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuarioItemStateChanged

    private void cb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btn_AperturaCaja;
    private javax.swing.JComboBox<String> cb_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jt_Cajas;
    public static javax.swing.JLabel lb_RazonSocial;
    private javax.swing.JLabel lb_errorAsunto;
    private javax.swing.JLabel lb_errorEmail;
    private javax.swing.JLabel lb_errorTelefono;
    // End of variables declaration//GEN-END:variables
}
