/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ModuloAdmin;


/**
 *
 * @author fenix
 */
public class Pn_PermisosAccesos extends javax.swing.JPanel {
   

    /**
     * Creates new form NuevoEmpleado1
     */
    public Pn_PermisosAccesos() {
        initComponents();
       
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jt_usuario = new javax.swing.JTextField();
        lb_errorStatus = new javax.swing.JLabel();
        lb_errorUsuario = new javax.swing.JLabel();
        lb_errorPassword = new javax.swing.JLabel();
        lb_errorNombre = new javax.swing.JLabel();
        lb_errorTelefono = new javax.swing.JLabel();
        lb_errorDireccion = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(84, 110, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Usuario");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total de registros ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 100, 20));

        jPanel2.setBackground(new java.awt.Color(84, 110, 122));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VISTA PARA EL CONTROL DE ACCESOS ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulario de Cambios");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalle de Empleados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1010, 10));

        jt_usuario.setBackground(new java.awt.Color(84, 110, 122));
        jt_usuario.setForeground(new java.awt.Color(204, 204, 204));
        jt_usuario.setText("Ingresar Usuario");
        jt_usuario.setBorder(null);
        jt_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jt_usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt_usuarioFocusLost(evt);
            }
        });
        jt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_usuarioMouseClicked(evt);
            }
        });
        jt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_usuarioKeyTyped(evt);
            }
        });
        jPanel1.add(jt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, -1));

        lb_errorStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorStatus.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorStatus.setText("*");
        jPanel1.add(lb_errorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 10, -1));

        lb_errorUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorUsuario.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorUsuario.setText("*");
        jPanel1.add(lb_errorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 10, -1));

        lb_errorPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorPassword.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorPassword.setText("*");
        jPanel1.add(lb_errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 10, -1));

        lb_errorNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorNombre.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorNombre.setText("*");
        jPanel1.add(lb_errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 10, -1));

        lb_errorTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorTelefono.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorTelefono.setText("*");
        jPanel1.add(lb_errorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 10, -1));

        lb_errorDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorDireccion.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorDireccion.setText("*");
        jPanel1.add(lb_errorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt_usuarioFocusGained
           // TODO add your handling code here:
    }//GEN-LAST:event_jt_usuarioFocusGained

    private void jt_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt_usuarioFocusLost
         // TODO add your handling code here:
    }//GEN-LAST:event_jt_usuarioFocusLost

    private void jt_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_usuarioMouseClicked
          // TODO add your handling code here:
    }//GEN-LAST:event_jt_usuarioMouseClicked

    private void jt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_usuarioKeyTyped

    }//GEN-LAST:event_jt_usuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JLabel lb_errorDireccion;
    private javax.swing.JLabel lb_errorNombre;
    private javax.swing.JLabel lb_errorPassword;
    private javax.swing.JLabel lb_errorStatus;
    private javax.swing.JLabel lb_errorTelefono;
    private javax.swing.JLabel lb_errorUsuario;
    // End of variables declaration//GEN-END:variables
}
