/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.ModuloAdmin;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import objetos.*;
import controladores.*;
import ds.desktop.notify.DesktopNotify;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import vistas.*;
/**
 *
 * @author fenix
 */
public class Pn_PermisosAccesos extends javax.swing.JPanel {
//NECESARIO PARA FUNCIONES DE ESTE MODULO 
    ControladorEstatusPermisos eperm = new ControladorEstatusPermisos();
    ControladorPermisos cperm = new ControladorPermisos();
    ControladorUsuarios cuser = new ControladorUsuarios();
    ControladorModulos cmod = new ControladorModulos();
    DefaultTableModel NewTable = new DefaultTableModel();
    //fin
    //variable que guarda el id del la fila del los privilegios de algun modulo
    private int idModUserPriv=0;
    //NECESARIO PARA MODIFICAR EL NOMBRE Y FUNCION DEL BOTON INGRESAR
    private int validador=0;
    //fin
    //NECESARIO PARA EL USO DE LA NOTIFICACION DINAMICA DE BOTON ELIMINAR ()
    Frame Principal;
    //FIN

    /**
     * Creates new form NuevoEmpleado1
     */
    public Pn_PermisosAccesos() {
        initComponents();
        eperm.tablaEstatusPermisos();
        cperm.tablaPermisos();
        cuser.tablaUsuarios();
        cmod.tablaModulos();
        cTabla();
        cargarUsuarios();
        cargarModulo();
        cargarConsultar();
        cargarAgregar();
        cargarActualizar();
        cargarEliminar();

    }

    public void datosIniciales() {
        idModUserPriv=0;
        cb_usuario.setSelectedIndex(0);
        cb_modulo.setSelectedIndex(0);
        cb_consultar.setSelectedIndex(0);
        cb_agregar.setSelectedIndex(0);
        cb_actualizar.setSelectedIndex(0);
        cb_eliminar.setSelectedIndex(0);
    }

    public void bloquearComponentes() {
        
        cb_modulo.setEnabled(false);
        cb_consultar.setEnabled(false);
        cb_agregar.setEnabled(false);
        cb_actualizar.setEnabled(false);
        cb_eliminar.setEnabled(false);
        btn_Modificar.setEnabled(false);
        btn_Eliminar.setEnabled(false);
    }

    public void desbloquearComponentes() {
        cb_modulo.setEnabled(true);
        cb_consultar.setEnabled(true);
        cb_agregar.setEnabled(true);
        cb_actualizar.setEnabled(true);
        cb_eliminar.setEnabled(true);
        btn_Modificar.setEnabled(true);
        btn_Eliminar.setEnabled(true);
    }

    public void cTabla() {
        jt_Privilegios.setModel(cperm.tablaPermisos());

    }

    public void cargarUsuarios() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Usuario");
        for (ObjetoUsuario campos : cuser.selectUsuario()) {
            cb.addElement(campos.getUsername());
        }
        cb_usuario.setModel(cb);

    }
        public void cargarModulo() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Módulo");
        for (ObjetoModulo campos : cmod.selectModulo()) {
            cb.addElement(campos.getNombre());
        }
        cb_modulo.setModel(cb);

    }

    public void cargarConsultar() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Permiso");
        for (ObjetoEstatusPermiso campos : eperm.selectEstatusPermiso()) {
            cb.addElement(campos.getNombre());
        }
        cb_consultar.setModel(cb);
     
    }
     public void cargarAgregar() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Permiso");
        for (ObjetoEstatusPermiso campos : eperm.selectEstatusPermiso()) {
            cb.addElement(campos.getNombre());
        }
      
        cb_agregar.setModel(cb);
      
    }
      public void cargarActualizar() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Permiso");
        for (ObjetoEstatusPermiso campos : eperm.selectEstatusPermiso()) {
            cb.addElement(campos.getNombre());
        }
       
        cb_actualizar.setModel(cb);
      
    }
       public void cargarEliminar() {

        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Seleccionar Permiso");
        for (ObjetoEstatusPermiso campos : eperm.selectEstatusPermiso()) {
            cb.addElement(campos.getNombre());
        }
 
        cb_eliminar.setModel(cb);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_errorStatus = new javax.swing.JLabel();
        lb_errorUsuario = new javax.swing.JLabel();
        lb_errorPassword = new javax.swing.JLabel();
        lb_errorNombre = new javax.swing.JLabel();
        lb_errorTelefono = new javax.swing.JLabel();
        lb_errorDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Privilegios = new javax.swing.JTable();
        btn_Ingresar = new principal.MaterialButton();
        btn_Modificar = new principal.MaterialButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Eliminar = new principal.MaterialButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_modulo = new javax.swing.JComboBox<>();
        cb_usuario = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        cb_consultar = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cb_actualizar = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cb_agregar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cb_eliminar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jch_facturacion = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(84, 110, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 110, 122));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VISTA PARA EL CONTROL DE ACCESOS ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1010, 10));

        lb_errorStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorStatus.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorStatus.setText("*");
        jPanel1.add(lb_errorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 10, -1));

        lb_errorUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorUsuario.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorUsuario.setText("*");
        jPanel1.add(lb_errorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 10, -1));

        lb_errorPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorPassword.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorPassword.setText("*");
        jPanel1.add(lb_errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 10, -1));

        lb_errorNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorNombre.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorNombre.setText("*");
        jPanel1.add(lb_errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 10, -1));

        lb_errorTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorTelefono.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorTelefono.setText("*");
        jPanel1.add(lb_errorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 10, -1));

        lb_errorDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_errorDireccion.setForeground(new java.awt.Color(84, 110, 122));
        lb_errorDireccion.setText("*");
        jPanel1.add(lb_errorDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 10, -1));

        jt_Privilegios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Privilegios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_PrivilegiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_Privilegios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 960, 180));

        btn_Ingresar.setBackground(new java.awt.Color(40, 180, 99));
        btn_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ingresar.setText("Agregar");
        btn_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Ingresar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 140, 40));

        btn_Modificar.setBackground(new java.awt.Color(255, 153, 0));
        btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Modificar.setText("Modificar");
        btn_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Modificar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons/limpiarCampos 24x24.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        btn_Eliminar.setBackground(new java.awt.Color(211, 18, 18));
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Eliminar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 140, 40));

        jPanel3.setBackground(new java.awt.Color(233, 235, 238));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Formulario de Cambios");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Privilegios");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Modulo");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, -1));

        cb_modulo.setBackground(new java.awt.Color(84, 110, 122));
        cb_modulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Modulo" }));
        cb_modulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_moduloItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_modulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, -1));

        cb_usuario.setBackground(new java.awt.Color(84, 110, 122));
        cb_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar usuario" }));
        cb_usuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuarioItemStateChanged(evt);
            }
        });
        cb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuarioActionPerformed(evt);
            }
        });
        jPanel3.add(cb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Usuario");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 390, 10));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Consultar");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        cb_consultar.setBackground(new java.awt.Color(84, 110, 122));
        cb_consultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Privilegio" }));
        cb_consultar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_consultarItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 170, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Modificar");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, -1));

        cb_actualizar.setBackground(new java.awt.Color(84, 110, 122));
        cb_actualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Privilegio" }));
        cb_actualizar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_actualizarItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Agregar");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, -1));

        cb_agregar.setBackground(new java.awt.Color(84, 110, 122));
        cb_agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Privilegio" }));
        cb_agregar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_agregarItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Eliminar");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        cb_eliminar.setBackground(new java.awt.Color(84, 110, 122));
        cb_eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Privilegio" }));
        cb_eliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_eliminarItemStateChanged(evt);
            }
        });
        jPanel3.add(cb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 390, 280));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tabla de Registros");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recomendaciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Generar Todos los Privilegios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, -1, 20));

        jch_facturacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jch_facturacionItemStateChanged(evt);
            }
        });
        jPanel1.add(jch_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Reestablecer Valores");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 325, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_moduloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_moduloItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            //this.idPiso = cb_modulo.getSelectedIndex();
        }
        //  System.out.println(cb_piso.getSelectedItem());
    }//GEN-LAST:event_cb_moduloItemStateChanged

    private void cb_consultarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_consultarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_consultarItemStateChanged

    private void cb_eliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_eliminarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_eliminarItemStateChanged

    private void cb_usuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuarioItemStateChanged

    private void cb_agregarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_agregarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_agregarItemStateChanged

    private void cb_actualizarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_actualizarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_actualizarItemStateChanged

    private void cb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_usuarioActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        try {
            if (validador == 1) {
                btn_Ingresar.setText("Generar");
                //codigo de generacion
                for (ObjetoUsuario user : cuser.selectUsuario()) {
                    for (ObjetoModulo mod : cmod.selectModulo()) {

                        cperm.insertPermiso(user.getUsername(), mod.getNombre(), "Permitido", "Permitido", "Permitido", "Permitido");
                        NewTable = new DefaultTableModel();
                        cTabla();

                    }

                }
            } else {
                
                btn_Ingresar.setText("Agregar");
                cperm.insertPermiso(String.valueOf(cb_usuario.getSelectedItem()), String.valueOf(cb_modulo.getSelectedItem()), String.valueOf(cb_consultar.getSelectedItem()), String.valueOf(cb_agregar.getSelectedItem()), String.valueOf(cb_actualizar.getSelectedItem()), String.valueOf(cb_eliminar.getSelectedItem()));
                NewTable = new DefaultTableModel();
                cTabla();
                
            }

        } catch (Exception e) {
            //DesktopNotify.showDesktopMessage("Error", "algo paso", DesktopNotify.ERROR);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        try {
            cperm.updatePermiso(String.valueOf(cb_usuario.getSelectedItem()), String.valueOf(cb_modulo.getSelectedItem()), String.valueOf(cb_consultar.getSelectedItem()), String.valueOf(cb_agregar.getSelectedItem()), String.valueOf(cb_actualizar.getSelectedItem()), String.valueOf(cb_eliminar.getSelectedItem()), idModUserPriv);
            NewTable = new DefaultTableModel();
            cTabla();
            datosIniciales();

        } catch (Exception e) {
            // DesktopNotify.showDesktopMessage("Error", "algo paso", DesktopNotify.ERROR);
        }


    }//GEN-LAST:event_btn_ModificarActionPerformed

    private void jt_PrivilegiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_PrivilegiosMouseClicked
        int seleccion = jt_Privilegios.rowAtPoint(evt.getPoint());
        //variable que guarda el id del la fila del los privilegios de algun modulo
        idModUserPriv = Integer.parseInt(String.valueOf(jt_Privilegios.getValueAt(seleccion, 0)));
        cb_usuario.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 1));
        cb_modulo.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 2));
        cb_consultar.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 3));
        cb_agregar.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 4));
        cb_actualizar.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 5));
        cb_eliminar.getModel().setSelectedItem(jt_Privilegios.getValueAt(seleccion, 6));
    }//GEN-LAST:event_jt_PrivilegiosMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        datosIniciales();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed

        try {
            if (idModUserPriv==0) {

                DesktopNotify.showDesktopMessage("Error", "DEBE SELECCIONAR UN ELEMENTO DE LA TABLA PARA PODER SER ELIMINADO", DesktopNotify.ERROR);

            } else {
                Pn_Alert_Eliminar ale = new Pn_Alert_Eliminar(Principal, true);
                ale.lb_titulo.setText("¿Esta seguro de eliminar este elemento?");
                ale.jb_aceptar.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                     cperm.deletePermiso(idModUserPriv);
                        NewTable = new DefaultTableModel();
                        cTabla();
                        datosIniciales();

                    }
                });
                ale.setVisible(true);
            }

        } catch (Exception e) {

    
        }

      
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void jch_facturacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jch_facturacionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {//checkbox has been selected
            validador = 1;
            bloquearComponentes();
        } else {//checkbox has been deselected
            validador = 0;
            desbloquearComponentes();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jch_facturacionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btn_Eliminar;
    private principal.MaterialButton btn_Ingresar;
    private principal.MaterialButton btn_Modificar;
    private javax.swing.JComboBox<String> cb_actualizar;
    private javax.swing.JComboBox<String> cb_agregar;
    private javax.swing.JComboBox<String> cb_consultar;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_modulo;
    private javax.swing.JComboBox<String> cb_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jch_facturacion;
    private javax.swing.JTable jt_Privilegios;
    private javax.swing.JLabel lb_errorDireccion;
    private javax.swing.JLabel lb_errorNombre;
    private javax.swing.JLabel lb_errorPassword;
    private javax.swing.JLabel lb_errorStatus;
    private javax.swing.JLabel lb_errorTelefono;
    private javax.swing.JLabel lb_errorUsuario;
    // End of variables declaration//GEN-END:variables
}
