/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilerias;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *Esta clase es necesaria para crear el menu dinámico en el menu superior de la pantalla recepciones 
 * @ fenix
 */
public class ComponenteMenuSuperior extends javax.swing.JPanel {


    private ActionListener act;
  public ComponenteMenuSuperior() {
        initComponents();
       
    }
     public JPanel ComponenteMenuSuperior(String menuName,int Separacion, ActionListener act) {

       //MODIFICACIONES DEL BOTON VISUALES
     
    //  lbAccesos.setIcon(Icon);
      lbAccesos.setText(menuName);
      lbAccesos.setIconTextGap(Separacion);
   
      
      ///TERMINA MODIFICACIONES DEL BOTON
        if (act != null) {
            this.act = act;
        }
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAccesos = new Utilerias.RSButtonMetro();

        setBackground(new java.awt.Color(28, 37, 47));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lbAccesos.setText("  boton vario");
        lbAccesos.setToolTipText("");
        lbAccesos.setColorBorde(null);
        lbAccesos.setColorHover(new java.awt.Color(111, 122, 134));
        lbAccesos.setColorNormal(new java.awt.Color(111, 122, 134));
        lbAccesos.setColorPressed(new java.awt.Color(111, 122, 134));
        lbAccesos.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        lbAccesos.setHideActionText(true);
        lbAccesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbAccesosMousePressed(evt);
            }
        });
        lbAccesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbAccesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAccesos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
 
    }//GEN-LAST:event_formMousePressed

    private void lbAccesosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAccesosMousePressed
      if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_lbAccesosMousePressed

    private void lbAccesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbAccesosActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_lbAccesosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Utilerias.RSButtonMetro lbAccesos;
    // End of variables declaration//GEN-END:variables
}
